spring.datasource.url=jdbc:postgresql://localhost:5432/hrms-training-module
spring.datasource.username=postgres
spring.datasource.password=Sanjhuk@04

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
file.upload-dir=uploads/certificates

server.port=${PORT:8080}
jwt.secret=2a$10$f/gfAhL4KaC2cZTiaDJizOrRjSx9QDdwePf8V6TV.ovC5VgcJg6CK
jwt.expiration-ms=86400000 